### ISSUE TITLE
[Testing on atten_sampler]

### ISSUE THREAD

**Issue by AlexHu123** [wkcn/AttentionSampler#3]
It is really a good work! 
Hi, I have tested on your demo on PyTorch. It works fine on cpu, but when I change torch.device('cpu') to torch.device('cuda'). It cannot be complied well. 
`[FATAL] /home/alexhu/Source/MobulaOP/mobula/./inc/context/./hip_ctx.h:82 Check Failed: cudaStreamSynchronize(stream) == cudaSuccess an illegal memory access was encountered`
My environment is `pytorch 1.2.0, mobula (the latest version on github), cuda 10.0, cudnn 7.5.0`.
Look forward to your reply !

**Comment by wkcn** [comment]
I have fixed the bug just now : )

**Comment by AlexHu123** [comment]
Sooo helpful of you! Thanks for your quick reply! I will try your latest version ASAP!
